# Generated by Django 5.2.6 on 2026-01-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('PROPOSAL', 'Proposal'), ('REIMBURSEMENT', 'Reimbursement'), ('LEAVE', 'Leave')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='requests/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Required for Reimbursement', max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Required for Leave', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Required for Leave', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='employees.employee')),
            ],
        ),
    ]
