# Generated by Django 5.2.6 on 2026-01-03 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_role'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='director_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='director_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='manager_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='manager_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NA', 'Not Applicable')], default='PENDING', max_length=15),
        ),
    ]
