# Generated by Django 5.2.6 on 2026-01-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_servicerequest_director_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='feedback',
            field=models.TextField(blank=True, help_text='Reason for rejection or approval notes', null=True),
        ),
    ]
