# Generated by Django 5.2.6 on 2026-01-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('KARYAWAN', 'Karyawan'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin'), ('DIREKTUR', 'Direktur')], default='KARYAWAN', max_length=20),
        ),
    ]
